### ISSUE TITLE
Generated short link can contain o

### ISSUE THREAD

**Issue by RobbertC5** [lgommans/dro.pm#2]
The short link `dro.pm/o` was generated although generated short links shouldn't contain any of `1 i 0 o`.

Screenshot:
![2019-04-18 16_58_37-dro pm url shortener](https://user-images.githubusercontent.com/14909256/56370925-66735c80-61fc-11e9-827d-bc7b40766f9d.png)

**Comment by lgommans** [comment]
Thanks for the report!
